# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
lang: zh-CN
timezone: Asia/Shanghai
# theme: jekyll-theme-chirpy
remote_theme: cotes2020/jekyll-theme-chirpy

title: Daomin's Blog
tagline: This is my blog world.

email: beyondcommunistparty@gmail.com
description: >- # used by seo meta and the atom feed
  This is my blog world.PHP.Java.Python.Go.Dart.Flutter
# baseurl: "" # the subpath of your site, e.g. /blog
baseurl: "https://blog.youcaitian.com" # the subpath of your site, e.g. /blog
url: "http://ly827.github.io/" # the base hostname & protocol for your site
avatar: https://avatars.githubusercontent.com/u/4003633?v=4

github:
  username: ly827
twitter:
  username: ly827
social:
  name: ly827
  email: beyondcommunistparty@gmail.com
  links:
    - https://github.com/ly827
    - https://twitter.com/ly827
theme_mode: light      # 或 dark

toc: true

comments:
  # Global switch for the post-comment system. Keeping it empty means disabled.
  provider: giscus # [disqus | utterances | giscus]
  # The provider options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: ly827/ly827.github.io # <gh-username>/<repo>
    repo_id: MDEwOlJlcG9zaXRvcnk0ODY3Nzc2OQ== # 48677769
    category: Comments
    category_id: DIC_kwDOAubDic4CpQfP # 44369871
    mapping: title # optional, default to 'pathname'
    strict: 0 # optional, default to '0'
    input_position: bottom # optional, default to 'bottom' "top"
    lang: zh-CN # optional, default to the value of `site.lang`
    reactions_enabled: 1 # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]

pwa:
  enabled: true # The option for PWA feature (installable)
  cache:
    enabled: true # The option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

sass:
  load_paths:
    - _sass

paginate: 10

# Build settings
markdown: kramdown
encoding: UTF-8
highlighter: rouge
plugins:
  # - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-include-cache


#paginate_path: "page:num"
 #   gems: [jekyll-paginate]
 #

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  input: GFM
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
